name: kitroom
version: '${project.version}'
main: blokplugins.kitroom.Kitroom
api-version: '1.20'
commands:
  kit:
    description: "opens kit menu"
    aliases:
      - kits
  kitroom:
    description: "opens up the kitroom"